import type { BonaFlowState } from "./types";

const seededAt = "2026-08-01T12:30:00.000+02:00";

export const SEED_STATE: BonaFlowState = {
  event: {
    id: "live",
    name: "8x Bella & Bona Mobile Hack",
    venue: "Delta Campus Berlin",
    lunchWindow: "12:30–14:00",
    dataDate: "1 Aug",
  },
  dishes: [
    {
      id: "chicken-pasta-salad",
      name: "Chicken Pasta Salad",
      allergens: ["gluten", "milk", "mustard", "sulphite"],
      dietTags: [],
      visible: [
        "penne",
        "chicken",
        "mozzarella pearls",
        "kalamata olives",
        "sun-dried tomato",
        "roasted red pepper",
        "herb dressing",
      ],
      image: "/dishes/chicken-pasta-salad.jpg",
    },
    {
      id: "mediterranean-cruise",
      name: "Mediterranean Cruise",
      allergens: ["milk", "gluten", "sulphite"],
      dietTags: ["vegetarian"],
      visible: [
        "rocket",
        "feta",
        "sun-dried tomato",
        "roasted red pepper",
        "balsamic",
      ],
      image: "/dishes/mediterranean-cruise.jpg",
    },
    {
      id: "high-protein-chicken-rice",
      name: "High Protein Chicken and Rice",
      allergens: ["celery"],
      dietTags: ["high_protein"],
      visible: [
        "grilled chicken",
        "rice",
        "cucumber",
        "cherry tomato",
        "pickled red cabbage",
        "tomato sauce",
      ],
      image: "/dishes/high-protein-chicken-rice.jpg",
    },
    {
      id: "thai-peanut-tofu-bowl",
      name: "High Protein Thai Peanut Bowl with Chickpea & Tofu",
      allergens: null,
      dietTags: ["vegan", "high_protein"],
      visible: [
        "tofu",
        "chickpeas",
        "sweetcorn",
        "carrot",
        "cucumber",
        "pickled red cabbage",
        "peanut sauce",
        "sesame seeds",
      ],
      image: "/dishes/thai-peanut-tofu-bowl.jpg",
    },
    {
      id: "vegan-chickpeas-quinoa-salad",
      name: "Vegan Chickpeas Quinoa Salad",
      allergens: ["mustard"],
      dietTags: ["vegan"],
      visible: [
        "chickpeas",
        "quinoa",
        "avocado",
        "cherry tomato",
        "roasted red pepper",
        "pumpkin seeds",
        "herb dressing",
      ],
      image: "/dishes/vegan-chickpeas-quinoa-salad.jpg",
    },
  ],
  stations: [
    {
      id: "station-a",
      name: "Main Hall",
      location: "main hall, left",
      queueLevel: "medium",
      status: "green",
      lastUpdatedAt: seededAt,
      dishes: [
        { dishId: "mediterranean-cruise", availability: "available" },
        { dishId: "chicken-pasta-salad", availability: "available" },
      ],
    },
    {
      id: "station-b",
      name: "Atrium",
      location: "by the stairs",
      queueLevel: "high",
      status: "orange",
      lastUpdatedAt: seededAt,
      dishes: [
        {
          dishId: "vegan-chickpeas-quinoa-salad",
          availability: "low",
        },
        { dishId: "thai-peanut-tofu-bowl", availability: "available" },
      ],
    },
    {
      id: "station-c",
      name: "Terrace",
      location: "back room",
      queueLevel: "low",
      status: "green",
      lastUpdatedAt: seededAt,
      dishes: [
        { dishId: "chicken-pasta-salad", availability: "available" },
        { dishId: "mediterranean-cruise", availability: "available" },
        { dishId: "thai-peanut-tofu-bowl", availability: "available" },
      ],
    },
    {
      id: "station-d",
      name: "Grab & Go",
      location: "near the entrance",
      queueLevel: "low",
      status: "green",
      lastUpdatedAt: seededAt,
      dishes: [
        {
          dishId: "high-protein-chicken-rice",
          availability: "available",
        },
      ],
    },
  ],
  alerts: [],
  tasks: [],
  incentive: {
    active: true,
    text: "Free coffee on the Terrace",
    appliesToStationId: "station-c",
    authorizedBy: "event_organiser",
    expiresAt: "2026-08-01T13:15:00.000+02:00",
  },
  staffUpdateCount: 0,
  recommendations: {
    all: "station-c",
    vegan: "station-c",
    vegetarian: "station-c",
    gluten_free: null,
    halal: null,
  },
  feedback: [],
};
